services:
- type: pserv
  name: elasticsearch
  env: docker
  autoDeploy: false # so ES does not restart on a push to this repository.
  envVars:
  - key: discovery.type
    value: single-node
  - key: cluster.name
    value: elastic
